version: '3'

services:
  log_assignment:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - log_network
    environment:
      - BATCH_SIZE=3
      - BATCH_INTERVAL=5
      - POST_ENDPOINT=https://httpdump.app/dumps/8e06d9f6-ac86-4629-a13b-f2d802a24fbe
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx_proxy:
    image: nginx
    networks:
      - log_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - log_assignment
    deploy:
      replicas: 1

networks:
  log_network:
    driver: bridge